server:
  port: 9091
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000

  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=orcl)))
    username: mytest
    password: mytest
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dbcp2:
      max-idle: 10
      max-wait-millis: 1000
      min-idle: 5
      initial-size: 5
mybatis:
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.fdm.testpoject.mapper: debug
